### ISSUE TITLE
Missing sourcefile from the blog ?

### ISSUE THREAD

**Issue by Carreau** [BIDS/docathon#15]
I can't seem to find the source file for the `participating` and `resources` section of the blog. 

Am I missing something ? 

cc @choldgraf ?

**Comment by choldgraf** [comment]
oops - just updated them. we're pushing to the website with ghp-import,
which pushes html to the `gh-pages` branch but doesn't update the master
branch. my bad
--

**Comment by Carreau** [comment]
> oops - just updated them. we're pushing to the website with ghp-import,
> which pushes html to the `gh-pages` branch but doesn't update the master
> branch. my bad

Thanks. We should setup travis to auto build and push at some point.

**Comment by choldgraf** [comment]
+1 - I'm not as experienced w/ setting up travis (mostly my experience with
travis is making him unhappy in my PRs :-D ) but happy to work with
somebody to get this set up

-- 

On Wed, Dec 7, 2016 at 12:17 PM Matthias Bussonnier <
notifications@github.com> wrote:

oops - just updated them. we're pushing to the website with ghp-import,
which pushes html to the gh-pages branch but doesn't update the master
branch. my bad

Thanks. We should setup travis to auto build and push at some point.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BIDS/docathon/issues/15#issuecomment-265561147>, or mute
the thread

**Comment by Carreau** [comment]
can you make me collaborator  so that I can experiment with setting up travis to build the blog ?

**Comment by choldgraf** [comment]
done! ![](http://cultofthepartyparrot.com/parrots/parrot.gif)

**Comment by Carreau** [comment]
Thanks.

**Comment by choldgraf** [comment]
Are you gonna use this issue to document setting up travis?

**Comment by choldgraf** [comment]
ah I see there's another issue for this, I'll close this one then
