### ISSUE TITLE
Give chris input on logo

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#18]

**Comment by Carreau** [comment]
It's not SVG !

**Comment by Carreau** [comment]
You can also make it Tikz.

**Comment by Carreau** [comment]
Also Happy birthday 🍰  !

**Comment by michaelpacer** [comment]
If you want it to appear to be triple quotes, you should have some tapering and a little more white space between the bars.

Also, party parrots hate Tikz.

**Comment by choldgraf** [comment]
@michaelpacer if you wanna play around with the design, an AI file is in the `media` folder on the google drive folder

**Comment by choldgraf** [comment]
what about that: 
![image](https://cloud.githubusercontent.com/assets/1839645/21122867/a93a14da-c089-11e6-9a66-f1c3628cac69.png)

or with parallel lines w/ the D:
![image](https://cloud.githubusercontent.com/assets/1839645/21122980/92ca8a1c-c08a-11e6-833a-964a2e3e4ac8.png)

**Comment by michaelpacer** [comment]
Definitely parallel lines with the D

is this version uploaded?

Is there a constraint that it be well inscribed by a square? (my guess and
inclination is yes but I wanted to make sure)

My instinct is squish the between quote space and make the counter for the
D bigger so that it's more prominently featured as a D.

Also my guess is this won't look good but i might take a stab at trying to
use halfwidth triple double quotes and not single quotes… but that might be
the kind of thinking that is [along the same lines as transparent green
lines with red ink in the shape of a kitten](
https://m.youtube.com/watch?v=BKorP55Aqvg)

**Comment by choldgraf** [comment]
Uploaded -> Yep it's in the google drive, not on the site yeet tho
Square -> yes probably

Quotes etc: let's just choose one of these now and then go with. We can always change it later and I don't want to spend all day fiddling with illustrator :)

![image](https://cloud.githubusercontent.com/assets/1839645/21149410/418f7988-c110-11e6-8a39-8d13a2c0a5d3.png)

**Comment by choldgraf** [comment]
OK, logo has vertical lines + SVG now, and is updated on the site:

![](https://bids.github.io/docathon/images/logo.svg)
