### ISSUE TITLE
Figure out groups.io

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#25]
hey @mrzv, can you give a quick breakdown of how groups.io would work for handling email communications etc? You seem to know the most about it :)

**Comment by mrzv** [comment]
There is not much to figure out. It's a normal mailing list. Send an email to docathon@group.io, and it will go to all subscribers (currently, eleven people). I'm happy to make anybody who wants to be a moderator. I haven't done it only to save people from getting extra spam (about subscribers and such).

The only substantive issue is how we want to use it. Any choice on the spectrum of "use it for all docathon related emails" to "only send 'important' follow-up emails after the docathon" makes sense. I personally would err towards the former, because I hate keeping track of CC lists on emails, but it's not a strong opinion. It's something we should decide as a group.

**Comment by choldgraf** [comment]
Yeah I think that's a good point, the list should be used for announcements and important info, but any project-specific conversation and day-of conversation should happen in either a gitter room or a github issue, IMO.

I'll send out a test email to see how it works today!

**Comment by choldgraf** [comment]
closing this since yes, it does work :)
