### ISSUE TITLE
Meeting Thursday, February 2nd at 12:00pm

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#28]
Hey folks, we have roughly a month until the docathon, so let's have a meeting to discuss our plan before the event. We've got the website finalized, as well as signup forms that we'll send out tomorrow morning (both for the participants as well as for projects).

# Agenda
At the meeting, here are a few topics we should discuss:

* Topics/speakers for the first day (#26)
* Structure of middle-days. e.g., specify ~3 hours of each day where we aim for people to be physically present in BIDS.
* Docathon project ideas for the organizing team. (#27)
* Communications leading up to the event.

Let me know if this time (**Thursday, Feb 2nd at noon**) doesn't work for you. If enough people can't make it then we can pick a different time.

# Meeting notes
* Twitter stuff
    * @teonbrooks is going to manage / keep an eye on the twitter account
    * @NelleV needs to make sure he has access
* Blog stuff
    * @mrzv  might help manage blog topics etc
    * We should create an issue to brainstorm topics, categories, etc
* Tools stuff
    * @NelleV  might build a super fancy new complicated tool BEFORE the docathon
    * @choldgraf + @NelleV  will build the infrastructure to scrape github activity 
* Planning each day
    * 2-6pm or so
    * Food ordered sometime in the middle
    * Figure out food situation
* Hacker within
    * Longer Travis tutorial from @Carreau here? We should open an issue on github for this.
* Gamifying
    * Stats 
    * Party parrot trophy
* First day
    * Morning tutorials - still need to finalize a list of topics and people to speak at them. @choldgraf can manage this but needs input from the rest of the team

Add anything else if I missed something!

**Comment by aliferg** [comment]
I can go

On Jan 31, 2017 1:55 PM, "Chris Holdgraf" <notifications@github.com> wrote:

Hey folks, we have roughly a month until the docathon, so let's have a
meeting to discuss our plan before the event. We've got the website
finalized, as well as signup forms that we'll send out tomorrow morning
(both for the participants as well as for projects).

At the meeting, here are a few topics we should discuss:

   - Topics/speakers for the first day (#26
   <https://github.com/BIDS/docathon/issues/26>)
   - Structure of middle-days. e.g., specify ~3 hours of each day where we
   aim for people to be physically present in BIDS.
   - Docathon project ideas for the organizing team. (#27
   <https://github.com/BIDS/docathon/issues/27>)
   - Communications leading up to the event.

@NelleV <https://github.com/NelleV> @stefanv <https://github.com/stefanv>
@Carreau <https://github.com/Carreau> @rlbarter
<https://github.com/rlbarter> @kevkoy <https://github.com/kevkoy>
@michaelpacer <https://github.com/michaelpacer> @mrzv
<https://github.com/mrzv> @aliferg <https://github.com/aliferg> @teonbrooks
<https://github.com/teonbrooks>

Let me know if this time (*Thursday, Feb 2nd at noon*) doesn't work for
you. If enough people can't make it then we can pick a different time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BIDS/docathon/issues/28>, or mute the thread

**Comment by teonbrooks** [comment]
+1. I should be able to make it IRL

**Comment by choldgraf** [comment]
great news!

**Comment by NelleV** [comment]
:+1:

**Comment by choldgraf** [comment]
Just a reminder we'll meet together **today at noon, in BIDS**. See you there!

**Comment by Carreau** [comment]
> Just a reminder we'll meet together today at noon, in BIDS. See you there!

Partial power outage at my place this morning, I need to make sure the fridge (at least) is on an extension cord and I'll be OMW. May be a bit late.

**Comment by aliferg** [comment]
I may be late to this, but feel free to carry on without me.

**Comment by Carreau** [comment]
Came across this recently: 

https://hackernoon.com/a-documentation-crash-course-45006a85c15c#.ulztav38m

**Comment by Carreau** [comment]
Also, contributors should register to https://codecuriosity.org

TL:DR; gamification -> points, points -> discount card on GitHub Shop an Amazon...

**Comment by stefanv** [comment]
@Carreau Good article, although I think the following example he gives is unfortunate:

> Let’s look at an example:
>
>    function takes parameter x and returns value y
>
> This describes what a function does in a clear, practical manner. But what about:
>
>    You can use function to return the value of y based on x

Simplicity, making things easy to read, is a much higher priority in my head than coming across all fuzzy and friendly.

**Comment by choldgraf** [comment]
hey all - see the updated top-level comment for meeting notes and to/dos. I'll check back in in a week to see what progress has been made by everybody. In the meantime I'm going to try and figure out a final list of topics / speakers for the first day. How much time per topic do you think we should give? 20 minutes? So 3 hours / 20 minutes = 9 tutorials we need to fill?
